version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  admin-service:
    build: ./admin-service
    container_name: admin-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  shop-service:
    build: ./shop-service
    container_name: shop-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server

